apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml

helmCharts:
  - name: vault-secrets-operator
    version: 0.9.0
    releaseName: vso
    repo: https://helm.releases.hashicorp.com
    #valuesFile: values.yaml
    namespace: vso
