apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml

helmCharts:
  - name: homarr
    version: 1.11.0
    releaseName: homarr
    repo: oci://ghcr.io/homarr-labs/charts/homarr
    valuesFile: values.yaml
    namespace: homarr
