apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  destination:
    namespace: awx
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app-of-apps/apps/awx
    repoURL: git@github.com:vdudejon/k8s-homelab2.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true