apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuma
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  project: default
  source:
    chart: kuma
    repoURL: kuma
    targetRevision: 2.9.0
    helm:
      releaseName: kuma
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kuma
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
