apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml

helmCharts:
  - name: vault
    # version: 0.14.1
    releaseName: vault
    repo: https://helm.releases.hashicorp.com
    valuesFile: values.yaml
    namespace: vault
