apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: px-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app-of-apps/operators/portworx
    repoURL: git@github.com:vdudejon/k8s-homelab2.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true