apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-issuer
  namespace: cert-manager
spec:
  acme:
    email: guts.creels.0n@icloud.com # icloud hide my email :)
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cluster-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: guts.creels.0n@icloud.com
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
