apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml

helmCharts:
  - name: external-secrets
    # version: 0.14.1
    releaseName: external-secrets
    repo: https://charts.external-secrets.io
    # valuesFile: values.yaml
    namespace: external-secrets
