apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml

helmCharts:
  - name: authentik
    # version: 0.14.1
    releaseName: authentik
    repo: https://charts.goauthentik.io
    valuesFile: values.yaml
    namespace: authentik
