apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: victoria-metrics-single
    # version: 0.14.1
    releaseName: victoriametrics
    repo: https://victoriametrics.github.io/helm-charts/
    # valuesFile: values.yaml
    namespace: victoriametrics
