apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

# Define the remote Helm chart details
helmCharts:
  - name: grafana
    # version: 0.14.1
    releaseName: grafana
    repo: https://grafana.github.io/helm-charts
    # valuesFile: values.yaml
    namespace: grafana
