# SOURCE: https://install.portworx.com/?operator=true&mc=false&kbver=1.25.0&ns=portworx&oem=esse&user=8f3ff411-990d-4b1d-a24a-7eb8fa28ed42&b=true&iop=6&c=px-cluster-746b08aa-da08-4bd0-b5fe-6f22e2b344c0&stork=true&csi=true&mon=true&tel=true&st=k8s&promop=true
kind: StorageCluster
apiVersion: core.libopenstorage.org/v1
metadata:
  name: px-cluster-746b08aa-da08-4bd0-b5fe-6f22e2b344c0
  namespace: portworx
  annotations:
    portworx.io/install-source: "https://install.portworx.com/?operator=true&mc=false&kbver=1.25.0&ns=portworx&oem=esse&user=8f3ff411-990d-4b1d-a24a-7eb8fa28ed42&b=true&iop=6&c=px-cluster-746b08aa-da08-4bd0-b5fe-6f22e2b344c0&stork=true&csi=true&mon=true&tel=true&st=k8s&promop=true"
    portworx.io/misc-args: "--oem esse"
spec:
  image: portworx/oci-monitor:3.1.6
  imagePullPolicy: Always
  kvdb:
    internal: true
  storage:
    useAll: true
  secretsProvider: k8s
  stork:
    enabled: true
    args:
      webhook-controller: "true"
  autopilot:
    enabled: true
  runtimeOptions:
    default-io-profile: "6"
  csi:
    enabled: true
  monitoring:
    telemetry:
      enabled: true
    prometheus:
      enabled: true
      exportMetrics: true