apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuma-ui-ingress
  namespace: kuma
  annotations:
    konghq.com/strip-path: "true"
spec:
  ingressClassName: "kong"
  rules:
    - host: kuma.apps.k8s.vdude.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kuma-control-plane
                port:
                  number: 5681
