apiVersion: v1
kind: Service
metadata:
  name: valheim-k8s
  namespace: valheim
spec:
  ports:
  - name: gameport
    port: 2456
    targetPort: 2456
    protocol: UDP
  - name: queryport
    port: 2457
    targetPort: 2457
    protocol: UDP
  - name: crossplayport
    port: 2458
    targetPort: 2458
    protocol: UDP
