apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-test-secret
  namespace: vso
spec:
  type: kv-v2
  # Mount path
  mount: kubernetes-secrets
  # Path of the secret
  path: test-secret
  # Dest k8s secret, as in this is the name of the secret that will be created in Kubernetes
  destination:
    name: k8s-test-secret
    create: true
  # Refresh interval.  The secret will auto update when it is changed in Vault
  refreshAfter: 30s
  # Name of the CRD to authenticate to Vault
  vaultAuthRef: vault-auth
