apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
  namespace: vso
spec:
  method: kubernetes
  mount: k8s-auth-mount
  kubernetes:
    role: k8s-read-all
    serviceAccount: vault-auth
    audiences:
      - vault
