apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevip
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  project: infrastructure
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  source:
    repoURL: 'https://github.com/vdudejon/k8s-homelab2.git'
    targetRevision: main
    path: argo-apps/projects/infrastructure/kubevip/overlays/dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
