apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

# Define the remote Helm chart details
helmCharts:
  - name: tandoor
    version: 2.16.1
    releaseName: tandoor
    repo: https://charts.gabe565.com
    # valuesFile: values.yaml
    namespace: tandoor
