apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/standard-install.yaml
  - gateway-class.yaml
  - gateway.yaml
  - namespace.yaml

# Define the remote Helm chart details
helmCharts:
  - name: ingress            # Name of the chart in the Helm repository
    version: 0.14.1       # Specific chart version to pull (optional)
    releaseName: kong      # Release name for the deployment
    repo: https://charts.konghq.com  # Remote Helm repository URL
    # valuesFile: values.yaml  # Path to your custom values file (if needed)
    namespace: kong         # Namespace where resources will be deployed
    apiVersions:
      - gateway.networking.k8s.io/v1
