apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-cd-ingress
  namespace: argo-cd
  annotations:
    konghq.com/strip-path: "true"
spec:
  ingressClassName: "kong"
  rules:
    - host: argo.apps.k8s.vdude.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argo-cd-argocd-server
                port:
                  number: 80
