apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml

helmCharts:
  - name: minio-operator
    # version: 0.14.1
    releaseName: minio-operator
    repo: https://operator.min.io
    valuesFile: values.yaml
    namespace: minio-operator
