apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  service_type: clusterip
  # ingress_type: ingress
  # ingress_class_name: kong
  # ingress_hosts:
  #   - hostname: awx.apps.k8s.vdude.io
  #     tls_secret: awx-cert
  postgres_data_volume_init: true
  postgres_init_container_commands: |
    chown 26:0 /var/lib/pgsql/data
    chmod 700 /var/lib/pgsql/data