apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  service_type: clusterip
  ingress_type: ingress
  ingress_hosts:
    - hostname: awx.apps.k8s.vdude.io
      tls_secret: aws-cert