apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# resources:
#   - namespace.yaml

# Define the remote Helm chart details
helmCharts:
  - name: sealed-secrets
    version: 2.16.1
    releaseName: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
    # valuesFile: values.yaml
    namespace: sealed-secrets
