apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# resources:
#   - namespace.yaml

helmCharts:
  - name: awx-operator
    version: 2.19.1
    releaseName: awx-operator
    repo: https://ansible-community.github.io/awx-operator-helm/
    namespace: awx
