apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml

helmCharts:
  - name: loki-stack
    # version: 0.14.1
    releaseName: loki
    repo: https://grafana.github.io/helm-charts
    valuesFile: values.yaml
    namespace: loki
patches:
  - path: patch-loki-jobs.yaml
    target:
      kind: Job
