apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# resources:
#   - namespace.yaml

helmCharts:
  - name: csi-driver-nfs
    version: 4.9.0
    releaseName: csi-driver-nfs
    repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    valuesFile: values.yaml
    namespace: kube-system
